### ISSUE TITLE
微信不能登录，不能注册用户

### ISSUE THREAD

**Issue by wzqwtt** [Mint-green/UnlearnableWord#1]
当点击微信登录之后，返回`Database error`，云数据库表都已创建。

```
{errorcode: -1, errormsg: "Database error!", err: {…}}
err: {}
errorcode: -1
errormsg: "Database error!"
__proto__: Object
```

**Comment by happyfox-dot** [comment]
> 当点击微信登录之后，返回`Database error`，云数据库表都已创建。
> 
> ```
> {errorcode: -1, errormsg: "Database error!", err: {…}}
> err: {}
> errorcode: -1
> errormsg: "Database error!"
> __proto__: Object
> ```
请问您解决了吗
