### ISSUE TITLE
求助老师 有一个报错解决不了

### ISSUE THREAD

**Issue by 6igg** [Mint-green/UnlearnableWord#10]
Error: cloud.callFunction:fail Error: errCode: -504003  | errMsg: Invoking task timed out after 3 seconds
![微信图片_20240425142007](https://github.com/Mint-green/UnlearnableWord/assets/168064475/6353e054-2389-4666-a012-6a6fe7273d6b)

**Comment by Mint-green** [comment]
来晚了不好意思，解决了是嘛

**Comment by 6igg** [comment]
> 来晚了不好意思，解决了是嘛

解决了，谢谢green老师
