### ISSUE TITLE
hei,  可以学习下你的项目吗，求个DB文件吗，礼貌star下

### ISSUE THREAD

**Issue by ruthlessHardt** [Mint-green/UnlearnableWord#2]

**Comment by Mint-green** [comment]
您好，我这个是用的微信的云开发数据库，json格式的数据信息，最近还是比较忙，我看看今天晚点有无时间整理下push一次，或者您看看怎么留下联系方式（好像可以找到我邮箱？），我直接发过去

**Comment by ruthlessHardt** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mint-green/UnlearnableWord"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月30日(星期六) 晚上9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mint-green/UnlearnableWord] hei,  可以学习下你的项目吗，求个DB文件吗，礼貌star下 (Issue #2)





 
您好，我这个是用的微信的云开发数据库，json格式的数据信息，最近还是比较忙，我看看今天晚点有无时间整理下push一次，或者您看看怎么留下联系方式（好像可以找到我邮箱？），我直接发过去

**Comment by ruthlessHardt** [comment]
好的，感谢，我的邮箱：ruthlesshardt@outlook.com

**Comment by Mint-green** [comment]
发送辽，有问题可以继续在这问哈哈哈~

**Comment by ruthlessHardt** [comment]
learner表需要有初始数据吗

**Comment by Mint-green** [comment]
learner表是不需要初始数据的，部署完成打开小程序使用前会提醒你登录，也可以进行注册，注册后用户数据会自动创建存到learner表（不过由于目前就只是简单写个用户的功能方便标记用户和存设置，密码那些没有用到啥加密措施）

**Comment by brentylw** [comment]
> 您好，我这个是用的微信的云开发数据库，json格式的数据信息，最近还是比较忙，我看看今天晚点有无时间整理下push一次，或者您看看怎么留下联系方式（好像可以找到我邮箱？），我直接发过去

同求数据库 文件，我的邮箱yanglinwei@gmail.com   谢谢！

**Comment by Junkk0921** [comment]
您好，可以同求一下数据库文件吗？我的邮箱是：2987861154@qq.com。非常非常感谢！！！

**Comment by Mint-green** [comment]
> 您好，可以同求一下数据库文件吗？我的邮箱是：[2987861154@qq.com](mailto:2987861154@qq.com)。非常非常感谢！！！

这个其实我在readme.md已经有说明啦
https://pan.baidu.com/s/1LR6Q6BojBTQ0ywWiJVFX6w
pwd：dddd

**Comment by Junkk0921** [comment]
好的，谢谢善良的博主啦~感恩


接淅
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mint-green/UnlearnableWord"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 上午10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mint-green/UnlearnableWord] hei,  可以学习下你的项目吗，求个DB文件吗，礼貌star下 (Issue #2)





 
Closed #2 as completed.

**Comment by Junkk0921** [comment]
请问可以加个联系方式吗？拜托了，有偿。
下载的是最新的代码，已经创建好了数据库，看到有人和我遇到了一样的问题，我还是没有解决









接淅
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mint-green/UnlearnableWord"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 上午10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mint-green/UnlearnableWord] hei,  可以学习下你的项目吗，求个DB文件吗，礼貌star下 (Issue #2)





 
这个其实我在readme.md已经有说明啦
 https://pan.baidu.com/s/1LR6Q6BojBTQ0ywWiJVFX6w
 pwd：dddd
  
***@***.***。非常非常感谢！！！

**Comment by Mint-green** [comment]
哈哈哈，可以的，先发个邮件到redupup@163.com吧
