### ISSUE TITLE
您好，体验很棒也很完善的项目，请问可以分享一份数据表相关文件吗

### ISSUE THREAD

**Issue by ZackYJz** [Mint-green/UnlearnableWord#3]
大佬您好！已 start，很喜欢您的这个项目，想用于学习小程序和云开发使用。能否分享一份 json 格式数据表文件或者其他相关文件吗？顺便求一波更新，感谢！
我的邮箱是 zackyjz@qq.com

**Comment by Mint-green** [comment]
数据库相关文件已经给你发过去啦，其他数据应该建好对应名字的kecollection（表）就可以正常使用产生数据了。
更新方面，暂时无力更新哈哈哈，有机会会继续努力的！有什么想到的功能也可以提一下鸭~

**Comment by cy920820** [comment]
同求，邮箱 cy920820@gmail.com，谢谢

**Comment by dukaiapper** [comment]
大佬您好！已 start，很喜欢您的这个项目，想用于学习小程序和云开发使用。能否分享一份 json 格式数据表文件或者其他相关文件吗？顺便求一波更新，感谢！
我的邮箱是 [dukaiapp@gmail.com](mailto:dukaiapp@gmail.com)

**Comment by collinswang** [comment]
大佬您好！已 start，很喜欢您的这个项目，想用于学习小程序和云开发使用。能否分享一份 json 格式数据表文件或者其他相关文件吗？顺便求一波更新，感谢！
我的邮箱是 452476865@qq.com

**Comment by keta1** [comment]
同求，邮箱 k@ketal.icu，谢谢
